#!/usr/bin/env python3
"""Assemble the Circle Take demo video — cinematic cut, fully automated.

Not a slideshow: the visual spine is REAL on-screen motion —
  - the Three.js "circle of takes" hero rotating (motion/hero.webm)
  - the autonomous roll scroll montage, Wan clips playing (motion/montage.webm)
  - the CUT clapper and the Anchor Gate QUARANTINE stamp animating in
  - the two real Wan clips (artifacts/live/take{1,2}_S02.mp4)
Detail close-ups use Ken Burns (slow zoom). Every cut is a crossfade.
Narration is macOS `say` (Samantha) — no mic, no copyrighted audio.

Inputs:
  scripts/demo/build/shots/*.png    (capture.mjs        — UI stills)
  scripts/demo/build/motion/*.webm  (capture_motion.mjs — UI motion)
  artifacts/live/take{1,2}_S02.mp4  (real Wan clips)

Output: artifacts/demo/circle-take-demo.mp4  (1080p30, target <= 180 s)

Arc = LIVE / honest: the Anchor Gate quarantines Take 2 (identity 15/100), and
that refusal is the point.
"""
from __future__ import annotations

import json
import os
import subprocess
import sys
import textwrap
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SHOTS = ROOT / "scripts/demo/build/shots"
MOTION = ROOT / "scripts/demo/build/motion"
CLIPS = ROOT / "artifacts/live"
WORK = ROOT / "scripts/demo/build/work"
OUT = ROOT / "artifacts/demo/circle-take-demo.mp4"
WORK.mkdir(parents=True, exist_ok=True)
OUT.parent.mkdir(parents=True, exist_ok=True)

W, H, FPS = 1920, 1080, 30
BG = "0x0b0b0d"
XF = 0.5    # crossfade duration between every beat
TAIL = 0.6  # silence kept after a line ends — paced to narration, no dead air
            # (>= XF so the crossfade never clips the voice tail)

# Narration: Qwen Cloud TTS (the demo's voice is itself generated by Qwen Cloud).
# Falls back to macOS `say` only if the API/key is unavailable.
QWEN_TTS_URL = os.environ.get(
    "QWEN_TTS_URL",
    "https://dashscope-intl.aliyuncs.com/api/v1/services/aigc/multimodal-generation/generation",
)
QWEN_TTS_MODEL = os.environ.get("QWEN_TTS_MODEL", "qwen3-tts-flash")
QWEN_TTS_VOICE = os.environ.get("QWEN_TTS_VOICE", "Ethan")
SAY_VOICE = os.environ.get("SAY_VOICE", "Samantha")
SAY_RATE = os.environ.get("SAY_RATE", "178")


def _qwen_key() -> str:
    k = os.environ.get("QWEN_API_KEY", "")
    if k:
        return k
    envf = ROOT / ".env.local"
    if envf.exists():
        for line in envf.read_text(encoding="utf-8").splitlines():
            if line.startswith("QWEN_API_KEY="):
                return line.split("=", 1)[1].strip().strip('"')
    return ""


QWEN_KEY = _qwen_key()

# Trim only the leading/trailing silence of a narration clip (TTS engines often
# bake in 1-2s of trailing silence). areverse twice => both ends; internal
# sentence pauses are preserved.
TRIM_SILENCE = (
    "silenceremove=start_periods=1:start_threshold=-40dB:start_silence=0.06,"
    "areverse,"
    "silenceremove=start_periods=1:start_threshold=-40dB:start_silence=0.06,"
    "areverse"
)

FONT = next(
    (f for f in ("/System/Library/Fonts/Supplemental/Arial.ttf",
                 "/Library/Fonts/Arial.ttf") if Path(f).exists()),
    "/System/Library/Fonts/Supplemental/Arial.ttf",
)
BOLD = next(
    (f for f in ("/System/Library/Fonts/Supplemental/Arial Bold.ttf",
                 FONT) if Path(f).exists()),
    FONT,
)

# Each beat: dict(id, kind, asset, dir?, caption, vo, dwell?)
#   kind "motion" -> clip (webm/mp4), filled/looped/slowed to seg length
#   kind "kb"     -> still with Ken Burns (dir: in|out)
#   kind "impact" -> CUT slam      kind "end" -> dimmed hero bg + title card
#   dwell (optional) = minimum seconds; without it a beat lasts vo + TAIL.
BEATS = [
    dict(id="b01", kind="motion", asset=CLIPS / "take1_S02.mp4", ss=0.0, to=5.0,
         caption="Take 1 — a generated shot.",
         vo="This is a generated episode. A clay micro drama. Meet Luna, a stop "
            "motion cat. Roll Take 1."),
    dict(id="b01b", kind="kb", asset=CLIPS / "take1_frame.png", dir="in", full=True,
         caption="Her markers — already gone.",
         vo="But watch closely. Her yellow bead eyes. Her white crescent patch. Her "
            "frayed red collar. Already gone."),
    dict(id="b02", kind="impact", asset=SHOTS / "05_scene.png",
         caption="It calls cut.", dwell=4.8,
         vo="Circle Take does not hide a bad take. It calls cut."),
    dict(id="b03", kind="kb", asset=SHOTS / "06_scene.png", dir="in",
         caption="A real Qwen verdict: FAIL.",
         vo="The take is not trusted. It is judged. Qwen's vision model returns a "
            "real verdict. Fail. Actor drift on Luna. The broken alarm clock, "
            "missing. Arthur, missing."),
    dict(id="b04", kind="motion", asset=MOTION / "hero.webm", dwell=8.0,
         caption="Circle Take — a self-correcting production loop.",
         vo="This is Circle Take. A self correcting production loop for generated "
            "episodes."),
    dict(id="b05", kind="motion", asset=MOTION / "montage.webm", dwell=12.0,
         caption="Catch. Reshoot only what failed. Remember only what's approved.",
         vo="Catch broken continuity. Reshoot only the failed shot. Remember only "
            "approved takes. The whole pipeline runs itself."),
    dict(id="b06", kind="kb", asset=SHOTS / "01_scene.png", dir="in",
         caption="It starts with a brief.",
         vo="It begins with a brief. A broken alarm clock learns it will be "
            "replaced, and a jealous cat hides the evidence."),
    dict(id="b07", kind="kb", asset=SHOTS / "02_scene.png", dir="in",
         caption="Identity contracts: the markers that must never drift.",
         vo="Scripty turns that brief into identity contracts. Each actor's fixed "
            "markers. Luna's bead eyes, her crescent patch, her frayed red collar. "
            "And the drifts that are forbidden."),
    dict(id="b08", kind="kb", asset=SHOTS / "03_scene.png", dir="out",
         caption="Every shot scored for identity risk — before a frame exists.",
         vo="Every shot is scored for identity risk before a single frame exists. "
            "Shot two is the danger. The clock strains, and Luna's markers can "
            "vanish."),
    dict(id="b09", kind="kb", asset=SHOTS / "04_scene.png", dir="in",
         caption="Different shots take different generation routes.",
         vo="Wan generates each shot. And it does not use one route for all of them. "
            "References for character critical frames. Targeted edits for repairable "
            "ones."),
    dict(id="b10", kind="kb", asset=SHOTS / "07_scene.png", dir="in",
         caption="The repair is a delta-only spell.",
         vo="When a shot fails, the fix is a delta only spell. Reshoot shot two. "
            "Restore every marker. Preserve the camera. Touch nothing else."),
    dict(id="b11", kind="motion", asset=CLIPS / "take2_S02.mp4", ss=3.0, to=5.0,
         caption="Wan reshoots — only shot two.", dwell=4.5,
         vo="Wan reshoots. But only shot two."),
    dict(id="b12", kind="kb", asset=SHOTS / "09_scene.png", dir="in",
         caption="Identity 15/100 → QUARANTINE.",
         vo="Take two faces the anchor gate. And here is the honest part. Identity "
            "scored fifteen out of a hundred. The reshoot still missed Luna. So the "
            "gate quarantines it. Circle Take refuses to greenlight an anchor that "
            "does not match. Even its own."),
    dict(id="b13", kind="kb", asset=SHOTS / "10_scene.png", dir="out",
         caption="Only approved anchors become memory.",
         vo="Only approved anchors become memory. The failure becomes a rule. Always "
            "preserve Luna's red ribbon. And the next episode, The Delivery Box, "
            "opens from what the show remembers."),
    dict(id="end", kind="end", asset=MOTION / "hero.webm", dwell=6.0,
         caption="",
         vo="Circle Take. Bad takes don't make the cut."),
]

END_TITLE = "CIRCLE TAKE"
END_SUB = "Bad takes don't make the cut."
END_URL = "github.com/ComBba/circle-take   ·   Built on Qwen Cloud   ·   Track 2: AI Showrunner"


def run(cmd: list) -> None:
    p = subprocess.run([str(c) for c in cmd], capture_output=True, text=True)
    if p.returncode != 0:
        sys.stderr.write(" ".join(str(c) for c in cmd) + "\n" + p.stderr[-1800:] + "\n")
        raise SystemExit(f"command failed: {cmd[0]}")


def probe_dur(path: Path) -> float:
    out = subprocess.check_output([
        "ffprobe", "-v", "error", "-show_entries", "format=duration",
        "-of", "default=nw=1:nk=1", str(path)])
    return float(out.strip())


def _qwen_tts(text: str, dst: Path) -> float | None:
    """Synthesize narration with Qwen Cloud TTS; None on any failure (caller falls back)."""
    if not QWEN_KEY:
        return None
    body = json.dumps({
        "model": QWEN_TTS_MODEL,
        "input": {"text": text, "voice": QWEN_TTS_VOICE, "language_type": "English"},
    }).encode()
    req = urllib.request.Request(
        QWEN_TTS_URL, data=body,
        headers={"Authorization": f"Bearer {QWEN_KEY}", "Content-Type": "application/json"},
    )
    try:
        with urllib.request.urlopen(req, timeout=90) as r:
            data = json.loads(r.read())
        url = data["output"]["audio"]["url"]
        src = dst.with_suffix(".src")
        with urllib.request.urlopen(url, timeout=90) as a, open(src, "wb") as f:
            f.write(a.read())
        run(["ffmpeg", "-y", "-i", src, "-af", TRIM_SILENCE, "-ar", "48000", "-ac", "2", dst])
        src.unlink(missing_ok=True)
        return probe_dur(dst)
    except Exception as e:  # noqa: BLE001 - any failure must fall back to local TTS
        sys.stderr.write(f"  [qwen-tts fallback -> say] {e}\n")
        return None


def tts(text: str, dst: Path) -> float:
    # Cache by exact text so rebuilds don't re-hit the paid TTS API.
    meta = dst.with_suffix(".votxt")
    if dst.exists() and meta.exists() and meta.read_text(encoding="utf-8") == text:
        return probe_dur(dst)
    d = _qwen_tts(text, dst)
    if d is None:
        aiff = dst.with_suffix(".aiff")
        run(["say", "-v", SAY_VOICE, "-r", SAY_RATE, "-o", aiff, text])
        run(["ffmpeg", "-y", "-i", aiff, "-af", TRIM_SILENCE, "-ar", "48000", "-ac", "2", dst])
        aiff.unlink(missing_ok=True)
        d = probe_dur(dst)
    meta.write_text(text, encoding="utf-8")
    return d


def caption_draw(caption: str, bid: str, size: int = 48) -> str:
    """drawtext filter (no leading comma) for a burnt-in lower-third caption."""
    capf = WORK / f"{bid}.txt"
    capf.write_text("\n".join(textwrap.wrap(caption, width=42)), encoding="utf-8")
    cf = str(capf).replace(":", r"\:")
    ff = FONT.replace(":", r"\:")
    return (
        f"drawtext=textfile='{cf}':fontfile='{ff}':fontsize={size}:fontcolor=white:"
        f"line_spacing=14:box=1:boxcolor=black@0.62:boxborderw=30:"
        f"x=(w-text_w)/2:y=h-text_h-86"
    )


def caption_vf(caption: str, bid: str, size: int = 48) -> str:
    return ("," + caption_draw(caption, bid, size)) if caption else ""


def kenburns_vf(direction: str, dur: float, full: bool = False) -> str:
    """Slow, centered Ken Burns zoom (no pan): subject stays centered, text never clips.

    Uses zoompan the canonical way (d = total frames over a single supersampled
    still) so the zoom actually accumulates frame-to-frame. full=True fills the
    frame (for a photo / clip keyframe); otherwise the still is a UI card on the
    dark background with generous margins.
    """
    n = max(int(round(dur * FPS)), 2)
    step = 0.085 / n  # reach ~1.085x by the end, regardless of beat length
    if direction == "out":  # gentle pull-back
        z = f"if(eq(on,0),1.085,max(zoom-{step:.6f},1.0))"
    else:                    # slow push-in
        z = f"min(zoom+{step:.6f},1.085)"
    if full:
        base = f"scale={W}:{H}:force_original_aspect_ratio=increase,crop={W}:{H},setsar=1"
    else:
        base = (f"scale=1480:800:force_original_aspect_ratio=decrease,"
                f"pad={W}:{H}:(ow-iw)/2:(oh-ih)/2:color={BG},setsar=1")
    return (
        f"{base},scale={W * 2}:{H * 2},"
        f"zoompan=z='{z}':d={n}:x='iw/2-(iw/zoom/2)':y='ih/2-(ih/zoom/2)':"
        f"s={W}x{H}:fps={FPS}"
    )


def build_segment(beat: dict) -> tuple[Path, float]:
    bid = beat["id"]
    wav = WORK / f"{bid}.wav"
    vo = tts(beat["vo"], wav)
    # Beat length is paced to the narration (vo + TAIL); `dwell` only sets a
    # minimum where the visual should breathe (landing, the CUT slam, a clip, the outro).
    seg_dur = round(max(vo + TAIL, beat.get("dwell", 0.0)), 2)
    seg = WORK / f"{bid}.mp4"
    cap = caption_vf(beat["caption"], bid)

    if beat["kind"] == "kb":
        vf = f"{kenburns_vf(beat['dir'], seg_dur, beat.get('full', False))}{cap}"
        run([
            "ffmpeg", "-y", "-loop", "1", "-framerate", FPS, "-t", seg_dur,
            "-i", beat["asset"], "-i", wav,
            "-vf", vf, "-af", "apad", "-map", "0:v", "-map", "1:a", "-t", seg_dur,
            "-c:v", "libx264", "-preset", "medium", "-pix_fmt", "yuv420p", "-r", FPS,
            "-c:a", "aac", "-ar", "48000", "-ac", "2", seg,
        ])
    elif beat["kind"] == "impact":
        # CUT! — a slam: punch-zoom (1.7x -> 1.0 in ~0.3s, then a hair of drift),
        # a decaying camera shake, and a white flash on frame one.
        n = max(int(round(seg_dur * FPS)), 2)
        punch = "if(lt(on,8),1.7-0.0875*on,min(1.0+0.004*(on-8),1.08))"
        shx = "iw/2-(iw/zoom/2)+sin(on*2.7)*max(0\\,16-1.5*on)"
        shy = "ih/2-(ih/zoom/2)+cos(on*3.1)*max(0\\,12-1.2*on)"
        fc = (
            f"[0:v]scale=1500:800:force_original_aspect_ratio=decrease,"
            f"pad={W}:{H}:(ow-iw)/2:(oh-ih)/2:color={BG},setsar=1,scale={W * 2}:{H * 2},"
            f"zoompan=z='{punch}':d={n}:x='{shx}':y='{shy}':s={W}x{H}:fps={FPS}[base];"
            f"[2:v]format=yuva420p,fade=t=out:st=0:d=0.16:alpha=1[flash];"
            f"[base][flash]overlay=0:0[bf];[bf]{caption_draw(beat['caption'], bid)}[v]"
        )
        run([
            "ffmpeg", "-y", "-loop", "1", "-framerate", FPS, "-t", seg_dur, "-i", beat["asset"],
            "-i", wav, "-f", "lavfi", "-t", seg_dur, "-i", f"color=white:s={W}x{H}:r={FPS}",
            "-filter_complex", fc, "-map", "[v]", "-map", "1:a", "-af", "apad", "-t", seg_dur,
            "-c:v", "libx264", "-preset", "medium", "-pix_fmt", "yuv420p", "-r", FPS,
            "-c:a", "aac", "-ar", "48000", "-ac", "2", seg,
        ])
    elif beat["kind"] == "end":
        ff = FONT.replace(":", r"\:")
        bf = BOLD.replace(":", r"\:")
        for nm, val in (("end_t.txt", END_TITLE), ("end_s.txt", END_SUB), ("end_u.txt", END_URL)):
            (WORK / nm).write_text(val, encoding="utf-8")
        t = str(WORK / "end_t.txt").replace(":", r"\:")
        s = str(WORK / "end_s.txt").replace(":", r"\:")
        u = str(WORK / "end_u.txt").replace(":", r"\:")
        vf = (
            f"scale={W}:{H}:force_original_aspect_ratio=increase,crop={W}:{H},"
            f"setsar=1,fps={FPS},eq=brightness=-0.34,"
            f"drawtext=textfile='{t}':fontfile='{bf}':fontsize=150:fontcolor=0xf3ecdf:"
            f"x=(w-text_w)/2:y=h/2-150,"
            f"drawtext=textfile='{s}':fontfile='{ff}':fontsize=58:fontcolor=0xe6324b:"
            f"x=(w-text_w)/2:y=h/2+40,"
            f"drawtext=textfile='{u}':fontfile='{ff}':fontsize=34:fontcolor=0xcfd6df:"
            f"x=(w-text_w)/2:y=h-150"
        )
        run([
            "ffmpeg", "-y", "-stream_loop", "-1", "-i", beat["asset"], "-i", wav,
            "-t", seg_dur, "-vf", vf, "-af", "apad", "-map", "0:v", "-map", "1:a",
            "-c:v", "libx264", "-preset", "medium", "-pix_fmt", "yuv420p", "-r", FPS,
            "-c:a", "aac", "-ar", "48000", "-ac", "2", seg,
        ])
    else:  # motion clip — optionally trim to a clean window and slow it to fill (no loop)
        ss, to = beat.get("ss"), beat.get("to")
        pre: list = []
        setpts = ""
        loop: list = ["-stream_loop", "-1"]
        if ss is not None and to is not None:
            pre = ["-ss", str(ss), "-to", str(to)]
            loop = []
            setpts = f"setpts={seg_dur / (to - ss):.4f}*PTS,"
        vf = (
            f"{setpts}scale={W}:{H}:force_original_aspect_ratio=increase,crop={W}:{H},"
            f"setsar=1,fps={FPS}{cap}"
        )
        run([
            "ffmpeg", "-y", *loop, *pre, "-i", beat["asset"], "-i", wav,
            "-t", seg_dur, "-vf", vf, "-af", "apad", "-map", "0:v", "-map", "1:a",
            "-c:v", "libx264", "-preset", "medium", "-pix_fmt", "yuv420p", "-r", FPS,
            "-c:a", "aac", "-ar", "48000", "-ac", "2", seg,
        ])

    print(f"  {bid:4} {beat['kind']:6} vo={vo:5.1f}s seg={seg_dur:5.1f}s  {beat['caption'][:42]}")
    return seg, seg_dur


def assemble(segs: list, durs: list, xfs: list) -> None:
    """Single ffmpeg pass: xfade video + acrossfade audio. xfs[k] = transition
    duration entering seg[k+1] (a near-zero value = hard cut, used around CUT)."""
    inputs: list = []
    for s in segs:
        inputs += ["-i", str(s)]

    vchain = []
    prev = "[0:v]"
    acc = durs[0]
    for k in range(1, len(segs)):
        xf = xfs[k - 1]
        out = f"[vx{k}]"
        off = acc - xf
        vchain.append(
            f"{prev}[{k}:v]xfade=transition=fade:duration={xf}:offset={off:.3f}{out}")
        prev = out
        acc = acc + durs[k] - xf
    total = acc
    vchain.append(f"{prev}fade=t=in:st=0:d=0.5,fade=t=out:st={total - 0.6:.2f}:d=0.6[vout]")

    achain = []
    prevA = "[0:a]"
    for k in range(1, len(segs)):
        out = f"[ax{k}]"
        achain.append(f"{prevA}[{k}:a]acrossfade=d={xfs[k - 1]}{out}")
        prevA = out
    achain.append(f"{prevA}afade=t=in:st=0:d=0.4,afade=t=out:st={total - 0.6:.2f}:d=0.6[aout]")

    fc = ";".join(vchain + achain)
    run([
        "ffmpeg", "-y", *inputs, "-filter_complex", fc,
        "-map", "[vout]", "-map", "[aout]",
        "-c:v", "libx264", "-preset", "slow", "-crf", "19", "-pix_fmt", "yuv420p",
        "-profile:v", "high", "-r", FPS,
        "-c:a", "aac", "-b:a", "192k", "-movflags", "+faststart", str(OUT),
    ])


def main() -> None:
    for b in BEATS:
        if not Path(b["asset"]).exists():
            raise SystemExit(f"missing asset: {b['asset']}")
    print("Building cinematic segments (TTS + ffmpeg motion/Ken Burns):")
    segs, durs = [], []
    for b in BEATS:
        s, d = build_segment(b)
        segs.append(s)
        durs.append(d)
    # Hard-cut the transitions touching the CUT slam so the punch lands clean.
    xfs = []
    for k in range(1, len(BEATS)):
        adjacent_impact = BEATS[k - 1]["kind"] == "impact" or BEATS[k]["kind"] == "impact"
        xfs.append(0.08 if adjacent_impact else XF)
    print("Assembling with crossfades...")
    assemble(segs, durs, xfs)
    final = probe_dur(OUT)
    flag = "OK <=180" if final <= 180 else "OVER 180!"
    print(f"\nDONE  {OUT.relative_to(ROOT)}  duration={final:.1f}s  ({flag})")


if __name__ == "__main__":
    main()
